web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=p@ssw0rd!
    ports:
     - "8081:80"
    volumes:
     - ~/Projects/PurAi/purai_wp_api/themes/server:/var/www/html/wp-content/themes/server

mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=p@ssw0rd!
     - MYSQL_DATABASE=wordpress